name: Deploy
on: 
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install project
      run: 
        npm install
    - name: FTP files to server
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        FTP_SERVER: "${{ secrets.FTP_SERVER }}"
        FTP_USERNAME: "${{ secrets.FTP_USERNAME }}"
        FTP_PASSWORD: "${{ secrets.FTP_PASSWORD }}"
        REMOTE_DIR: "DOCmeAPI"
  smoke-test:
    runs-on: ubuntu-latest
    name: Smoke Test
    needs: deploy
    steps:
    - name: Check Sign-In endpoint
      uses: srt32/uptime@master
      with:
        url-to-hit: "http://www.docmeapp.com/user/signin"
        expected-statuses: "405"
