name: Deploy
on: 
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install project
      run: 
        npm install
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v1.1.0
      with:
        host: "${{ secrets.FTP_SERVER }}"
        user: "${{ secrets.FTP_USERNAME }}"
        password: "${{ secrets.FTP_PASSWORD }}"
        remoteDir: "DOCmeAPI"
